# Generated by Django 4.2.7 on 2023-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_alter_supervisor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='melodie',
            field=models.BigIntegerField(default=1),
        ),
    ]
