# Generated by Django 4.2.7 on 2023-12-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0004_alter_supervisor_melodie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='mel',
        ),
    ]
