# Generated by Django 4.2.7 on 2023-12-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0005_remove_supervisor_mel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='melodie',
        ),
        migrations.AlterModelTable(
            name='supervisor',
            table='useri',
        ),
    ]
