# Generated by Django 4.2.7 on 2023-12-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysongs',
            name='comp_path',
            field=models.CharField(max_length=250),
        ),
    ]
