# Generated by Django 4.2.7 on 2023-12-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0005_remove_supervisor_mel'),
        ('songs', '0002_alter_mysongs_comp_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysongs',
            name='mel',
            field=models.ManyToManyField(to='supervisor.supervisor'),
        ),
        migrations.AlterModelTable(
            name='mysongs',
            table=None,
        ),
    ]
