# Generated by Django 4.2.7 on 2023-12-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_mysongs_mel_alter_mysongs_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mysongs',
            table='mysongs',
        ),
    ]
